version: '2.3'
services:
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"
  jaeger:
    image: jaegertracing/all-in-one:1.24
    command: --log-level=debug
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

  service:
    image: arruda/adaptive-publisher:master
    command: ./adaptive_publisher/run.py
    depends_on:
      - redis
      - jaeger
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${SERVICE_STREAM_KEY}
      - REGISTER_EVAL_DATA=${REGISTER_EVAL_DATA}
      - EVENT_GENERATOR_TYPE=${EVENT_GENERATOR_TYPE}
      - EARLY_FILTERING_PIPELINE_NAME=${EARLY_FILTERING_PIPELINE_NAME}
      - DEFAULT_OI_LIST=${DEFAULT_OI_LIST}
      - USE_OCV_TRANSFORMS=${USE_OCV_TRANSFORMS}
      - DEFAULT_CACHED_FRAME_RATE_MULTIPLIER=${DEFAULT_CACHED_FRAME_RATE_MULTIPLIER}
      - DEFAULT_DIFF_THRESHOLD=${DEFAULT_DIFF_THRESHOLD}
      - DEFAULT_CLS_THRESHOLDS=${DEFAULT_CLS_THRESHOLDS}
      - DEFAULT_OBJ_THRESHOLD=${DEFAULT_OBJ_THRESHOLD}
      - CLS_MODEL_ID=${CLS_MODEL_ID}
      - PUBLISHER_INPUT_SOURCE=${PUBLISHER_INPUT_SOURCE}
      - PUBLISHER_ID=${PUBLISHER_ID}
      - PUBLISHER_FPS=${PUBLISHER_FPS}
      - PUBLISHER_RESOLUTION=${PUBLISHER_RESOLUTION}
      - LISTEN_EVENT_TYPE_EARLY_FILTERING_UPDATED=${LISTEN_EVENT_TYPE_EARLY_FILTERING_UPDATED}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    volumes:
      - ./data:/service/data